# MAINTAINER  张钦博

global:
  scrape_interval: 10s
  evaluation_interval: 10s


alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 127.0.0.1:9093

rule_files:
  - rules/*yml


scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-expor"
    static_configs:
      - targets: ["10.33.12.209:9100","10.33.12.20:9100"]


  - job_name: "process-expor"
    static_configs:
      - targets: ["10.33.12.209:9256","10.33.12.20:9256"]

  - job_name: 'prod-federate'
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="prometheus"}'
        - '{job="process"}'
        - '{job="node"}'
        - '{job="state-metrics"}'
        - '{job="cadvisor"}'
        - '{job="kubernetes-apiservers"}'
        - '{job="kubernetes-nodes"}'
        - '{job="kubernetes-service-endpoints-slow"}'
        - '{job="kubernetes-services"}'
        - '{job="kubernetes-pods"}'
        - '{job="kubernetes-pods-slow"}'
    static_configs:
      - targets: ["10.33.13.12:20800"]

  - job_name: 'test-federate'
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="prometheus"}'
        - '{job="process"}'
        - '{job="node"}'
        - '{job="state-metrics"}'
        - '{job="cadvisor"}'
        - '{job="kubernetes-apiservers"}'
        - '{job="kubernetes-nodes"}'
        - '{job="kubernetes-service-endpoints-slow"}'
        - '{job="kubernetes-services"}'
        - '{job="kubernetes-pods"}'
        - '{job="kubernetes-pods-slow"}'
    static_configs:
      - targets: ["10.33.66.20:30800"]

  - job_name: "ping"
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
    - refresh_interval: 20s
      files:
      - "/etc/blackbox/icmp.yaml"
    relabel_configs:
    - source_labels: [__address__]
      regex: (.*)(:80)?
      target_label: __param_target
      replacement: ${1}
    - source_labels: [__param_target]
      target_label: instance
    - source_labels: [__param_target]
      regex: (.*)
      target_label: ping
      replacement: ${1}
    - source_labels: []
      regex: .*
      target_label: __address__
      replacement: 10.33.12.20:9115

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    tls_config:
      insecure_skip_verify: true
    file_sd_configs: 
    - refresh_interval: 1m
      files: 
      - "/etc/blackbox/http.yaml"
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 10.33.12.20:9115
